<a href="https://colab.research.google.com/github/liraaricardo/exercicios-biblioteca-python/blob/main/Exercicios_PythonBiblioteca__Ricardo_Lira_6B_Noturno_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1 Exercıcios de NumPy**

1. Crie um array unidimensional de 50 elementos contendo n´umeros inteiros
aleat´orios entre 10 e 100.

In [6]:
import numpy as np

array = np.random.randint(10, 101, size=50)
print("Array:", array)

Array: [47 86 90 75 40 13 47 69 79 55 85 85 85 97 39 31 39 94 24 73 32 60 92 21
 92 46 23 71 79 79 19 47 30 53 76 34 50 41 23 52 52 67 10 70 30 77 12 60
 91 93]


Explicação: np.random.randint(10, 101, size=50) gera 50 inteiros aleatórios no intervalo [10, 100] (o limite superior é exclusivo, por isso é usado 101).

2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima
linha.

In [7]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)
print("Matriz:\n", matriz)

ultima_linha = matriz[-1, :]
print("Última linha:", ultima_linha)

Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Última linha: [13 14 15 16]


Explicação: np.arange(1, 17) cria os números de 1 a 16, e reshape(4, 4) organiza em matriz 4x4. matriz[-1, :] seleciona a última linha.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posi¸c˜ao por 1

In [8]:
import numpy as np

array = np.zeros(15)
array[4:10] = 1  # índices 4 a 9 correspondem às posições 5ª a 10ª
print("Array:", array)

Array: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Explicação: Como os índices em Python começam em 0, a 5ª posição é o índice 4 e a 10ª posição é o índice 9. O fatiamento [4:10] cobre exatamente esse intervalo.

4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e
a moda dos valores.

In [9]:
import numpy as np
from scipy import stats

array = np.random.randint(1, 101, size=100)

mediana = np.median(array)
moda = stats.mode(array, keepdims=True)

print("Array:", array)
print("Mediana:", mediana)
print("Moda:", moda.mode[0], "- Frequência:", moda.count[0])

Array: [40 63 23  8 68 74 50  8 44 60 13 13 71 17 44 48  1  5  3 62 55 85 13 11
 65 93 82 86 14 82 64 27 50 89 15  5 47 36 88 73 98 27  7 98 28  7 32 66
 57 54 88  9 79 84 15 83 20 46 75 49 92 56 28 46 93 44 40 20 49 66  4 26
 53 76 92 41 56  9 18 51 99 49 23 59 25 62 41 87 55 37 51 94 32 46  6 66
 65  8 87  9]
Mediana: 49.0
Moda: 8 - Frequência: 3


Explicação: NumPy não tem função nativa de moda, por isso é usado scipy.stats.mode. np.median() calcula a mediana normalmente.

5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua
todos os valores multiplos de 3 por-3

In [10]:
import numpy as np

array = np.random.randint(1, 101, size=20)
print("Original:", array)

array[array % 3 == 0] = -3
print("Modificado:", array)

Original: [26 69 27 72 67 20 27 42 38 91 15 42 71 86 78 28 90 17 93 54]
Modificado: [26 -3 -3 -3 67 20 -3 -3 38 91 -3 -3 71 86 -3 28 -3 17 -3 -3]


Explicação: array % 3 == 0 cria uma máscara booleana identificando os múltiplos de 3, usada para indexação e substituição direta dos valores.

6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma
de cada coluna

In [11]:
import numpy as np

matriz = np.random.rand(5, 5)
print("Matriz:\n", matriz)

soma_colunas = np.sum(matriz, axis=0)
print("Soma de cada coluna:", soma_colunas)

Matriz:
 [[0.81832011 0.41615382 0.65526545 0.70886427 0.69141625]
 [0.69754536 0.17390368 0.06656874 0.02227744 0.65995378]
 [0.62266774 0.06082535 0.37780034 0.60389018 0.57596513]
 [0.42397207 0.35805211 0.80700101 0.73429388 0.97297115]
 [0.662747   0.18750106 0.1125045  0.89283178 0.43314174]]
Soma de cada coluna: [3.22525227 1.19643602 2.01914004 2.96215755 3.33344805]


Explicação: axis=0 indica que a soma é feita ao longo das linhas (ou seja, resultando em um valor por coluna).

7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.

In [12]:
import numpy as np

array1 = np.random.rand(20)
array2 = np.random.rand(20)

correlacao = np.corrcoef(array1, array2)
print("Matriz de correlação:\n", correlacao)
print("Coeficiente de correlação:", correlacao[0, 1])

Matriz de correlação:
 [[ 1.         -0.07790754]
 [-0.07790754  1.        ]]
Coeficiente de correlação: -0.07790754079627593


Explicação: np.corrcoef() retorna uma matriz de correlação; o valor de interesse (correlação entre os dois arrays) está na posição [0, 1].

8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus
elementos ao quadrado.

In [13]:
import numpy as np

matriz = np.random.randint(1, 20, size=(3, 3))
print("Matriz original:\n", matriz)

matriz_quadrado = matriz ** 2
print("Matriz ao quadrado:\n", matriz_quadrado)

Matriz original:
 [[10 12 11]
 [ 9 19  9]
 [ 7 13 17]]
Matriz ao quadrado:
 [[100 144 121]
 [ 81 361  81]
 [ 49 169 289]]


Explicação: A operação ** 2 é aplicada elemento por elemento, aproveitando a vetorização do NumPy (sem necessidade de laços).

9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0
e 1.

In [14]:
import numpy as np

array = np.random.randint(1, 100, size=10)
print("Original:", array)

normalizado = (array - np.min(array)) / (np.max(array) - np.min(array))
print("Normalizado:", normalizado)

Original: [38 13 28 88 97 83  2 15 56 64]
Normalizado: [0.37894737 0.11578947 0.27368421 0.90526316 1.         0.85263158
 0.         0.13684211 0.56842105 0.65263158]


Explicação: A fórmula de normalização Min-Max reescala os valores para o intervalo [0, 1], subtraindo o mínimo e dividindo pela amplitude (máximo - mínimo).

10. Crie umamatriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.

In [15]:
import numpy as np

matriz = np.eye(6)
print("Identidade original:\n", matriz)

np.fill_diagonal(matriz, np.arange(1, 7))
print("Diagonal modificada:\n", matriz)

Identidade original:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Diagonal modificada:
 [[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Explicação: np.eye(6) cria a matriz identidade e np.fill_diagonal() substitui os valores da diagonal principal pela sequência de 1 a 6.

11. Gere um array de 100 numeros inteiros e encontre o valor que mais se
repete no array.





In [16]:
import numpy as np
from scipy import stats

array = np.random.randint(1, 50, size=100)
print("Array:", array)

moda = stats.mode(array, keepdims=True)
print("Valor mais frequente:", moda.mode[0], "- Ocorrências:", moda.count[0])

Array: [14 49 12 40 49 16 29 16  3 39 38 33  3 49 42  7 27 12 27 17 27 41 17 27
 28 29 32 48 15 40 24 28 27 42 12 20 23 18 18 16 16 22 30 28 33 12 12 15
 23 32 43  4 10  6 41 28 16 22 21 45 30  3 38 40 18 44  6  6 16 14  9 15
 21 19 42 44  6 47 25  9  6 44 19  5 36  9 18 35  6 43 25 30  3 48 48 33
  9 33 33 39]
Valor mais frequente: 6 - Ocorrências: 6


Explicação: Assim como no exercício da mediana/moda, é usado scipy.stats.mode para encontrar o valor que mais se repete, já que o NumPy puro não tem uma função nativa para isso.

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7

In [17]:
import numpy as np

matriz = np.random.randint(1, 20, size=(4, 4))
print("Matriz original:\n", matriz)

np.fill_diagonal(matriz, 7)
print("Matriz com diagonal = 7:\n", matriz)

Matriz original:
 [[ 8 10  2 16]
 [ 7 10  8 13]
 [15  1  1  8]
 [16 13  2 16]]
Matriz com diagonal = 7:
 [[ 7 10  2 16]
 [ 7  7  8 13]
 [15  1  7  8]
 [16 13  2  7]]


Explicação: np.fill_diagonal() permite substituir os valores da diagonal principal por um valor único (7, neste caso) diretamente na matriz original.

13. Crie um array contendo os 10 primeiros numeros pares e calcule sua soma
cumulativa

In [18]:
import numpy as np

array = np.arange(2, 21, 2)
print("Array de pares:", array)

soma_cumulativa = np.cumsum(array)
print("Soma cumulativa:", soma_cumulativa)

Array de pares: [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: [  2   6  12  20  30  42  56  72  90 110]


Explicação: np.arange(2, 21, 2) gera os números pares de 2 a 20 (os 10 primeiros pares). np.cumsum() calcula a soma acumulada elemento a elemento.

14. Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo
comprimento e encontre a media das diferencas

In [19]:
import numpy as np

array1 = np.random.randint(1, 100, size=20)
array2 = np.random.randint(1, 100, size=20)

diferenca = array1 - array2
print("Array 1:", array1)
print("Array 2:", array2)
print("Diferença:", diferenca)

media_diferencas = np.mean(diferenca)
print("Média das diferenças:", media_diferencas)

Array 1: [90 88 36 71 27 95 45 41 38 86 21 97  6 94 87 28 31  2  9 90]
Array 2: [53 55 26 28 90 76 45 38 87 77 60  3 74 92 45 18 66 42 45 45]
Diferença: [ 37  33  10  43 -63  19   0   3 -49   9 -39  94 -68   2  42  10 -35 -40
 -36  45]
Média das diferenças: 0.85


Explicação: A subtração entre arrays é feita elemento por elemento; np.mean() calcula a média dos resultados.

15. Gere um array contendo 20 n´umeros e substitua todos os valores maiores
que 50 por 50

In [20]:
import numpy as np

array = np.random.randint(1, 100, size=20)
print("Original:", array)

array[array > 50] = 50
print("Modificado:", array)

Original: [73 89 54 53 27 86 43 71 72 18 88  1 42 19 23 49 64 46 19 90]
Modificado: [50 50 50 50 27 50 43 50 50 18 50  1 42 19 23 49 50 46 19 50]


Explicação: A máscara booleana array > 50 identifica os valores acima do limite, que são então substituídos por 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4

In [21]:
import numpy as np

array = np.arange(1, 13)
print("Array unidimensional:", array)

matriz = array.reshape(3, 4)
print("Matriz 3x4:\n", matriz)

Array unidimensional: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Explicação: Um array de 12 elementos é necessário para reorganizar em 3x4 (3 × 4 = 12). reshape() transforma a estrutura sem alterar os dados.

17. Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada
valor por sua posicao na matriz.


In [22]:
import numpy as np

matriz = np.random.randint(1, 10, size=(4, 4))
print("Matriz original:\n", matriz)

linhas, colunas = np.indices((4, 4))
posicoes = linhas * colunas
print("Matriz de posições:\n", posicoes)

resultado = matriz * posicoes
print("Resultado:\n", resultado)

Matriz original:
 [[4 5 3 9]
 [4 7 5 8]
 [2 7 1 3]
 [6 1 3 2]]
Matriz de posições:
 [[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
Resultado:
 [[ 0  0  0  0]
 [ 0  7 10 24]
 [ 0 14  4 18]
 [ 0  3 18 18]]


Explicação: np.indices((4, 4)) gera duas matrizes com os índices de linha e coluna. Multiplicando-as, obtemos a "posição" de cada elemento, que é usada para multiplicar a matriz original.

18. Crie um array de 10 elementos contendo n´umeros entre 1 e 100 e substitua
todos os valores m´ultiplos de 5 por 0.

In [23]:
import numpy as np

array = np.random.randint(1, 101, size=10)
print("Original:", array)

array[array % 5 == 0] = 0
print("Modificado:", array)

Original: [50 16 23 18 42 28 54 98 95 10]
Modificado: [ 0 16 23 18 42 28 54 98  0  0]


Explicação: A máscara array % 5 == 0 identifica múltiplos de 5, que são zerados por indexação booleana.

19. Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o
angulo entre eles (produto escalar normalizado)

In [24]:
import numpy as np

array1 = np.random.randint(1, 20, size=20)
array2 = np.random.randint(1, 20, size=20)

produto_escalar = np.dot(array1, array2)
norma1 = np.linalg.norm(array1)
norma2 = np.linalg.norm(array2)

cos_theta = produto_escalar / (norma1 * norma2)
angulo_rad = np.arccos(cos_theta)
angulo_graus = np.degrees(angulo_rad)

print("Array 1:", array1)
print("Array 2:", array2)
print("Cosseno do ângulo:", cos_theta)
print("Ângulo (graus):", angulo_graus)

Array 1: [15  4 15  4  8  2 14  4  8 15  3  4 11 12  6 12 15 10  4  8]
Array 2: [12  7 16  2 10 19  2 10  3 14  3  9  7  7  2 15  7  3  9 15]
Cosseno do ângulo: 0.7965945703350982
Ângulo (graus): 37.193872691117974


Explicação: O cosseno do ângulo entre dois vetores é dado pelo produto escalar dividido pelo produto das normas. np.arccos() converte o cosseno em radianos, e np.degrees() converte para graus.

20. Crie uma matriz de numeros inteiros e encontre o valor mınimo de cada
linha

In [25]:
import numpy as np

matriz = np.random.randint(1, 100, size=(5, 4))
print("Matriz:\n", matriz)

minimos_por_linha = np.min(matriz, axis=1)
print("Mínimo de cada linha:", minimos_por_linha)

Matriz:
 [[10 63 49 56]
 [34 76 77 40]
 [80 39 18 34]
 [63 77 37  5]
 [31 25 49 26]]
Mínimo de cada linha: [10 34 18  5 25]


Explicação: axis=1 indica que a operação np.min() é feita ao longo das colunas de cada linha, retornando um valor mínimo por linha.

## **2 Exercıcios de SciPy**

1. Calcule a integral da funcao f(x) = x2 sin(x) no intervalo de 0 a π.

In [26]:
from scipy import integrate
import numpy as np

def f(x):
    return x**2 * np.sin(x)

resultado, erro = integrate.quad(f, 0, np.pi)
print("Resultado da integral:", resultado)
print("Erro estimado:", erro)

Resultado da integral: 5.869604401089359
Erro estimado: 6.516569951530559e-14


Explicação: integrate.quad() calcula a integral numérica definida no intervalo especificado, retornando o resultado e uma estimativa do erro.

2. Resolva a equacao diferencial dy
dx = x−y, com y(0) = 1, no intervalo de 0
a 10.

In [27]:
from scipy.integrate import solve_ivp
import numpy as np

def eq_diferencial(x, y):
    return x - y

solucao = solve_ivp(eq_diferencial, [0, 10], [1], t_eval=np.linspace(0, 10, 100))

print("x:", solucao.t)
print("y:", solucao.y[0])

x: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818

Explicação: solve_ivp resolve a EDO numericamente. t_eval define os pontos onde queremos avaliar a solução, gerando uma curva suave.

3. Encontre as raızes da funcao f(x) = x4 − 3x3 + 2 utilizando SciPy

In [28]:
from scipy.optimize import fsolve
import numpy as np

def f(x):
    return x**4 - 3*x**3 + 2

estimativas = [-1, 0.5, 1, 3]
raizes = [fsolve(f, x0)[0] for x0 in estimativas]

print("Raízes encontradas:", raizes)

Raízes encontradas: [np.float64(0.999999999999979), np.float64(0.9999999999999999), np.float64(1.0), np.float64(2.919639565839426)]


Explicação: Como fsolve encontra uma raiz por vez a partir de um ponto inicial, usamos várias estimativas para tentar localizar diferentes raízes da equação (função de grau 4 pode ter até 4 raízes reais).

4. Use a funcao de otimizacao de SciPy para maximizar f(x) = −x2+4x+1.

In [29]:
from scipy.optimize import minimize

def f_negativa(x):
    return -(-x**2 + 4*x + 1)

resultado = minimize(f_negativa, 0)
x_max = resultado.x[0]
valor_max = -resultado.fun

print("x que maximiza:", x_max)
print("Valor máximo:", valor_max)

x que maximiza: 2.000000026187685
Valor máximo: 4.999999999999999


5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e
cos(4πt)

In [30]:
from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 500)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

frequencias = fft(sinal)
print("Transformada de Fourier:", frequencias)

Transformada de Fourier: [ 1.00000000e+00-0.00000000e+00j  2.90072788e+00-2.49734797e+02j
  2.50215500e+02+3.81342503e+00j -8.12691279e-01+3.60703450e-01j
 -3.41694941e-01+2.58792067e-01j -1.97819842e-01+2.02703677e-01j
 -1.31921837e-01+1.66976721e-01j -9.55896332e-02+1.42117536e-01j
 -7.32353312e-02+1.23775301e-01j -5.84308766e-02+1.09662581e-01j
 -4.80902980e-02+9.84565861e-02j -4.05690038e-02+8.93369898e-02j
 -3.49205772e-02+8.17670771e-02j -3.05671755e-02+7.53804686e-02j
 -2.71389515e-02+6.99182812e-02j -2.43898744e-02+6.51922740e-02j
 -2.21509238e-02+6.10622230e-02j -2.03027689e-02+5.74214885e-02j
 -1.87591576e-02+5.41875046e-02j -1.74564597e-02+5.12953343e-02j
 -1.63468833e-02+4.86931934e-02j -1.53939572e-02+4.63392748e-02j
 -1.45694511e-02+4.41994519e-02j -1.38512331e-02+4.22455899e-02j
 -1.32217515e-02+4.04542837e-02j -1.26669407e-02+3.88059032e-02j
 -1.21754202e-02+3.72838604e-02j -1.17379015e-02+3.58740416e-02j
 -1.13467423e-02+3.45643622e-02j -1.09956079e-02+3.33444140e-02j


6. Encontre a matriz inversa de uma matriz 5x5 de numeros aleatorios

In [31]:
from scipy.linalg import inv
import numpy as np

matriz = np.random.rand(5, 5)
print("Matriz original:\n", matriz)

inversa = inv(matriz)
print("Matriz inversa:\n", inversa)

Matriz original:
 [[0.5669753  0.89327087 0.40526142 0.8032492  0.24296066]
 [0.48272727 0.9679658  0.13170347 0.21375496 0.65222764]
 [0.28990878 0.40469058 0.94635981 0.3667687  0.49458113]
 [0.88726753 0.2566636  0.9451947  0.51049155 0.5873937 ]
 [0.52551678 0.43976475 0.95123801 0.17147078 0.98861525]]
Matriz inversa:
 [[-2.10022048  2.21690684  0.86206963  2.77325413 -3.02545644]
 [-1.81421649  2.74253965  3.07679177  0.58809479 -3.2521684 ]
 [-2.06984359  1.441557    3.5359176   1.06891622 -2.84641125]
 [ 4.86000571 -4.42939729 -4.46674549 -2.44284913  5.41390337]
 [ 3.07206926 -3.01719566 -4.45439166 -2.34057835  5.86619065]]


7. Use a funcao de interpolacao cubica de SciPy para interpolar os dados
(0, 0), (1,2),(2,3),(3,5),(4,4).

In [32]:
from scipy.interpolate import interp1d
import numpy as np

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

f_cubica = interp1d(x, y, kind='cubic')

x_novos = np.linspace(0, 4, 20)
y_novos = f_cubica(x_novos)

print("Valores interpolados:", y_novos)

Valores interpolados: [0.         0.6776498  1.18851144 1.56524275 1.84050153 2.04694562
 2.21723283 2.38402099 2.57996793 2.83773145 3.18821986 3.62210235
 4.08980901 4.54002041 4.92141712 5.18267969 5.2724887  5.13952471
 4.73246829 4.        ]


8. Resolva o sistema de equacoes 3x + 2y = 5 e x+4y = 6

In [33]:
from scipy import linalg
import numpy as np

A = np.array([[3, 2], [1, 4]])
B = np.array([5, 6])

solucao = linalg.solve(A, B)
print("Solução [x, y]:", solucao)

Solução [x, y]: [0.8 1.3]


9. Ajuste uma curva quadratica aos pontos (1,2),(2,4),(3,5),(4,7),(5,8).

In [34]:
from scipy.optimize import curve_fit
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

def quadratica(x, a, b, c):
    return a * x**2 + b * x + c

parametros, _ = curve_fit(quadratica, x, y)
print("Parâmetros [a, b, c]:", parametros)

Parâmetros [a, b, c]: [-0.07142857  1.92857143  0.2       ]


10. Calcule a integral dupla da funcao f(x,y) = xy + x2 no intervalo [0,2]
para x e [0,1] para y.

In [35]:
from scipy import integrate

def f(y, x):
    return x*y + x**2

resultado, erro = integrate.dblquad(f, 0, 2, 0, 1)

print("Resultado da integral dupla:", resultado)
print("Erro estimado:", erro)

Resultado da integral dupla: 3.666666666666667
Erro estimado: 5.5294392329864537e-14


11. Encontre os autovalores e autovetores de uma matriz 4x4 de numeros
inteiros aleatorios.

In [36]:
from scipy import linalg
import numpy as np
matriz = np.random.randint(1, 10, size=(4, 4))
print("Matriz:\n", matriz)

autovalores, autovetores = linalg.eig(matriz)

print("Autovalores:", autovalores)
print("Autovetores:\n", autovetores)


Matriz:
 [[6 3 8 3]
 [1 5 5 2]
 [8 1 9 9]
 [7 7 2 8]]
Autovalores: [21.80380063+0.j          1.12722913+4.32922257j  1.12722913-4.32922257j
  3.9417411 +0.j        ]
Autovetores:
 [[-0.48475837+0.j          0.32092891-0.35430077j  0.32092891+0.35430077j
  -0.65036587+0.j        ]
 [-0.28555483+0.j          0.28402284-0.18194059j  0.28402284+0.18194059j
   0.32827925+0.j        ]
 [-0.66777621+0.j          0.13559965+0.45770262j  0.13559965-0.45770262j
  -0.20131713+0.j        ]
 [-0.48738351+0.j         -0.65561062+0.j         -0.65561062-0.j
   0.65477354+0.j        ]]


12. Resolva a equacao ex − x2 = 0 para encontrar a raiz mais proxima de
x =1.

In [37]:
from scipy.optimize import fsolve
import numpy as np
def f(x):
    return np.exp(x) - x**2

raiz = fsolve(f, 1)
print("Raiz encontrada:", raiz)

Raiz encontrada: [-0.70346742]


13.Calcule o determinante de uma matriz 6x6 de numeros aleatorios entre-10 e 10.

In [38]:
from scipy import linalg
import numpy as np

matriz = np.random.randint(-10, 11, size=(6, 6))
print("Matriz:\n", matriz)

determinante = linalg.det(matriz)
print("Determinante:", determinante)

Matriz:
 [[ -8  -8  -6  -9   4  -4]
 [  7  -3   1   2  -6   2]
 [ -4 -10  -3  -4  -5  -9]
 [  2  -8 -10   3  -3  -6]
 [  4  -7   1  10   2  -9]
 [  8  -4  -5  -1   6  -2]]
Determinante: -860580.9999999999


14. Utilize a funcao de otimizacao multivariada para minimizar f(x,y) = (x−
2)2 +(y −3)2.

In [39]:
from scipy.optimize import minimize

def funcao(v):
    x, y = v
    return (x - 2)**2 + (y - 3)**2

resultado = minimize(funcao, [0, 0])
print("Mínimo encontrado em [x, y]:", resultado.x)

Mínimo encontrado em [x, y]: [1.99999999 2.99999999]


 15.Calcule a transformada de Fourier inversa de um sinal complexo gerado
aleatoriamente.

In [40]:
from scipy.fft import fft, ifft
import numpy as np

sinal_complexo = np.random.rand(50) + 1j * np.random.rand(50)
print("Sinal original:", sinal_complexo[:5], "...")

sinal_transformado = fft(sinal_complexo)
sinal_reconstruido = ifft(sinal_transformado)

print("Sinal reconstruído:", sinal_reconstruido[:5], "...")

Sinal original: [0.57150006+0.2267764j  0.82588262+0.92242385j 0.8389138 +0.6285487j
 0.9437617 +0.63406468j 0.25208957+0.19482416j] ...
Sinal reconstruído: [0.57150006+0.2267764j  0.82588262+0.92242385j 0.8389138 +0.6285487j
 0.9437617 +0.63406468j 0.25208957+0.19482416j] ...


16. Resolva a equacao diferencial de segunda ordem d2y
dx2
+y = 0, comcondicoes
iniciais y(0) = 1 e y′(0) = 0.

In [1]:
from scipy.integrate import solve_ivp
import numpy as np

# Transformar em sistema de 1ª ordem: y1 = y, y2 = y'
def sistema(x, estado):
    y1, y2 = estado
    dy1_dx = y2
    dy2_dx = -y1
    return [dy1_dx, dy2_dx]

solucao = solve_ivp(sistema, [0, 10], [1, 0], t_eval=np.linspace(0, 10, 100))

print("x:", solucao.t)
print("y:", solucao.y[0])  # solução y(x) -- essa é a função cosseno

x: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818

17. Encontre a raiz cubica de 27 utilizando SciPy.

In [2]:
from scipy.optimize import fsolve
import numpy as np

def f(x):
    return x**3 - 27

raiz = fsolve(f, 1)
print("Raiz cúbica de 27:", raiz)

# Alternativa direta, sem otimização:
print("Verificação direta:", 27 ** (1/3))

Raiz cúbica de 27: [3.]
Verificação direta: 3.0


18.Interpole os valores de uma funcao f(x) = x2 nos pontos [1,2,3,4,5]
utilizando spline cubica

In [ ]:
from scipy.interpolate import interp1d
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = x**2  # f(x) = x²

f_spline = interp1d(x, y, kind='cubic')

x_novos = np.linspace(1, 5, 20)
y_novos = f_spline(x_novos)

print("Valores interpolados:", y_novos)

 19.Realize a transformada de Fourier de um sinal discreto composto de senos
e cossenos.

In [ ]:
from scipy.fft import fft
import numpy as np

n = np.arange(64)  # sinal discreto com 64 amostras
sinal = np.sin(2 * np.pi * n / 16) + np.cos(2 * np.pi * n / 8)

frequencias = fft(sinal)
print("Transformada de Fourier:", frequencias)

20. Resolva um sistema de equacoes lineares com tres variaveis utilizando
SciPy

In [ ]:
from scipy import linalg
import numpy as np
A = np.array([[2, 1, -1],
              [1, -1, 2],
              [3, 2, 1]])
B = np.array([3, 1, 8])

solucao = linalg.solve(A, B)
print("Solução [x, y, z]:", solucao)

# **3. Exercıcios de Pandas**

1. Crie um DataFrame contendo as colunas Produto, Preco e Quantidade
com 5 produtos.

In [2]:
import pandas as pd

dados = {
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset'],
    'Preço': [3500, 80, 150, 900, 250],
    'Quantidade': [10, 50, 30, 15, 20]
}
df = pd.DataFrame(dados)
print(df)

    Produto  Preço  Quantidade
0  Notebook   3500          10
1     Mouse     80          50
2   Teclado    150          30
3   Monitor    900          15
4   Headset    250          20


2. Leia um arquivo Excel chamado vendas.xlsx e exiba as 10 primeiras
linhas.

In [1]:
import pandas as pd

df = pd.read_excel('vendas.xlsx')
print(df.head(10))

FileNotFoundError: [Errno 2] No such file or directory: 'vendas.xlsx'